columns:
  characters:
    - name
    - summary
    - space
    - description
    - experiences_offered
    - neighborhood_overview
    - notes
    - transit
    - access
    - interaction
    - house_rules
    - host_id
    - host_location
    - host_about
    - host_verifications
    - street
    - amenities
    - license
    - jurisdiction_names
  logicals:
    - host_is_superhost
    - host_has_profile_pic
    - host_identity_verified
    - is_location_exact
    - has_availability
    - requires_license
    - instant_bookable
    - is_business_travel_ready
    - require_guest_profile_picture
    - require_guest_phone_verification
  categoricals:
    - host_neighbourhood
    - neighbourhood_cleansed
    - city
    - state
    - neighbourhood_group_cleansed
    - smart_location
    - country_code
    - market
    - property_type
    - room_type
    - bed_type
    - cancellation_policy
    - calendar_updated
    - host_response_time
  numericals:
    - host_response_rate
    - host_acceptance_rate
    - latitude
    - longitude
    - square_feet
    - price
    - security_deposit
    - cleaning_fee
    - extra_people
    - reviews_per_month
  integers:
    - host_listings_count
    - host_total_listings_count
    - accommodates
    - guests_included
    - bathrooms
    - bedrooms
    - beds
    - minimum_nights
    - maximum_nights
    - availability_30
    - availability_60
    - availability_90
    - availability_365
    - number_of_reviews
    - review_scores_rating
    - review_scores_accuracy
    - review_scores_cleanliness
    - review_scores_checkin
    - review_scores_communication
    - review_scores_location
    - review_scores_value
    - calculated_host_listings_count
  dates:
    - last_scraped
    - host_since
    - first_review
    - last_review
long_list:
  - host_since
  - host_response_time
  - host_response_rate
  - host_is_superhost
  - host_total_listings_count
  - host__has_profile_pic
  - host_identity_verified
  - street
  - neighbourhood_cleansed
  - neighboourhood_group_cleansed
  - latitude
  - longitude
  - is_location_exact
  - property_type
  - room_type
  - accommodates
  - bathrooms
  - bedrooms
  - beds
  - bed_type
  - has_tv
  - has_internet
  - has_wifi
  - has_parking
  - price
  - security_deposit
  - cleaning_fee
  - guests_included
  - extra_people
  - minimum_nights
  - maximum_nights
  - calendar_updated_cleansed
  - availability_30
  - availability_60
  - availability_90
  - availability_365
  - number_of_reviews
  - first_review
  - last_review
  - review_period
  - review_scores_rating
  - review_scores_accuracy
  - review_scores_cleanliness
  - review_scores_checkin
  - review_scores_communication
  - review_scores_location
  - review_scores_value
  - instant_bookable
  - cancellation_policy
  - calculated_host_listings_count
  - reviews_per_month
...
